version: "2"
services:
  db:
    image: linuxserver/mariadb:version-110.4.17mariabionic
    container_name: mariadb
    environment:
      - MYSQL_USER=develop
      - MYSQL_PASSWORD=develop
      - MYSQL_DATABASE=develop
    ports:
      - 3306:3306/tcp
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379